version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: jquery
    versions:
    - 3.5.1
